Search.appendIndex(
    [
                {
            "fqsen": "\\Database",
            "name": "Database",
            "summary": "",
            "url": "classes/Database.html"
        },                {
            "fqsen": "\\Database\u003A\u003A__clone\u0028\u0029",
            "name": "__clone",
            "summary": "",
            "url": "classes/Database.html#method___clone"
        },                {
            "fqsen": "\\Database\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor\u0020para\u0020conectarme\u0020a\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/Database.html#method___construct"
        },                {
            "fqsen": "\\Database\u003A\u003AgetDatabase\u0028\u0029",
            "name": "getDatabase",
            "summary": "Patr\u00F3n\u0020singleton\u0020para\u0020crear\u0020solo\u0020una\u0020instancia\u0020de\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/Database.html#method_getDatabase"
        },                {
            "fqsen": "\\Database\u003A\u003AsqlQuery\u0028\u0029",
            "name": "sqlQuery",
            "summary": "Funci\u00F3n\u0020que\u0020devuelve\u0020el\u0020resultado\u0020de\u0020la\u0020consulta\u0020pasada\u0020por\u0020par\u00E1metro",
            "url": "classes/Database.html#method_sqlQuery"
        },                {
            "fqsen": "\\Database\u003A\u003AgetObject\u0028\u0029",
            "name": "getObject",
            "summary": "Recibo\u0020el\u0020objeto\u0020de\u0020la\u0020consulta",
            "url": "classes/Database.html#method_getObject"
        },                {
            "fqsen": "\\Database\u003A\u003Aescape\u0028\u0029",
            "name": "escape",
            "summary": "Escapo\u0020la\u0020cadena\u0020para\u0020evitar\u0020fallos\u0020de\u0020seguridad",
            "url": "classes/Database.html#method_escape"
        },                {
            "fqsen": "\\Database\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "Destructor\u0020para\u0020cerrar\u0020la\u0020conexi\u00F3n\u0020con\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/Database.html#method___destruct"
        },                {
            "fqsen": "\\Database\u003A\u003AHOST",
            "name": "HOST",
            "summary": "",
            "url": "classes/Database.html#constant_HOST"
        },                {
            "fqsen": "\\Database\u003A\u003AUSER",
            "name": "USER",
            "summary": "",
            "url": "classes/Database.html#constant_USER"
        },                {
            "fqsen": "\\Database\u003A\u003APASS",
            "name": "PASS",
            "summary": "",
            "url": "classes/Database.html#constant_PASS"
        },                {
            "fqsen": "\\Database\u003A\u003ANAME",
            "name": "NAME",
            "summary": "",
            "url": "classes/Database.html#constant_NAME"
        },                {
            "fqsen": "\\Database\u003A\u003A\u0024database",
            "name": "database",
            "summary": "",
            "url": "classes/Database.html#property_database"
        },                {
            "fqsen": "\\Database\u003A\u003A\u0024sqli",
            "name": "sqli",
            "summary": "",
            "url": "classes/Database.html#property_sqli"
        },                {
            "fqsen": "\\Database\u003A\u003A\u0024que",
            "name": "que",
            "summary": "",
            "url": "classes/Database.html#property_que"
        },                {
            "fqsen": "\\Session",
            "name": "Session",
            "summary": "",
            "url": "classes/Session.html"
        },                {
            "fqsen": "\\Session\u003A\u003A__clone\u0028\u0029",
            "name": "__clone",
            "summary": "",
            "url": "classes/Session.html#method___clone"
        },                {
            "fqsen": "\\Session\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Session.html#method___construct"
        },                {
            "fqsen": "\\Session\u003A\u003AstartSession\u0028\u0029",
            "name": "startSession",
            "summary": "Patr\u00F3n\u0020singleton\u0020para\u0020iniciar\u0020la\u0020sesi\u00F3n",
            "url": "classes/Session.html#method_startSession"
        },                {
            "fqsen": "\\Session\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "Comprueba\u0020si\u0020el\u0020login\u0020del\u0020usuario\u0020se\u0020hace\u0020correctamente",
            "url": "classes/Session.html#method_login"
        },                {
            "fqsen": "\\Session\u003A\u003AisExpired\u0028\u0029",
            "name": "isExpired",
            "summary": "Comprueba\u0020si\u0020la\u0020sesi\u00F3n\u0020ha\u0020expirado\u0020por\u0020tiempo",
            "url": "classes/Session.html#method_isExpired"
        },                {
            "fqsen": "\\Session\u003A\u003AisLogged\u0028\u0029",
            "name": "isLogged",
            "summary": "Comprueba\u0020si\u0020la\u0020sesi\u00F3n\u0020esta\u0020logeada",
            "url": "classes/Session.html#method_isLogged"
        },                {
            "fqsen": "\\Session\u003A\u003Aredirect\u0028\u0029",
            "name": "redirect",
            "summary": "Redirige\u0020a\u0020la\u0020ruta\u0020que\u0020se\u0020le\u0020indique",
            "url": "classes/Session.html#method_redirect"
        },                {
            "fqsen": "\\Session\u003A\u003Aclose\u0028\u0029",
            "name": "close",
            "summary": "Cierra\u0020y\u0020destruye\u0020la\u0020sesi\u00F3n",
            "url": "classes/Session.html#method_close"
        },                {
            "fqsen": "\\Session\u003A\u003AEXPIRE_TIME",
            "name": "EXPIRE_TIME",
            "summary": "",
            "url": "classes/Session.html#constant_EXPIRE_TIME"
        },                {
            "fqsen": "\\Session\u003A\u003A\u0024session",
            "name": "session",
            "summary": "",
            "url": "classes/Session.html#property_session"
        },                {
            "fqsen": "\\Session\u003A\u003A\u0024time",
            "name": "time",
            "summary": "",
            "url": "classes/Session.html#property_time"
        },                {
            "fqsen": "\\OpClass",
            "name": "OpClass",
            "summary": "",
            "url": "classes/OpClass.html"
        },                {
            "fqsen": "\\OpClass\u003A\u003AgetClassId\u0028\u0029",
            "name": "getClassId",
            "summary": "",
            "url": "classes/OpClass.html#method_getClassId"
        },                {
            "fqsen": "\\OpClass\u003A\u003AgetClassName\u0028\u0029",
            "name": "getClassName",
            "summary": "",
            "url": "classes/OpClass.html#method_getClassName"
        },                {
            "fqsen": "\\OpClass\u003A\u003AsetClassName\u0028\u0029",
            "name": "setClassName",
            "summary": "",
            "url": "classes/OpClass.html#method_setClassName"
        },                {
            "fqsen": "\\OpClass\u003A\u003AallClasses\u0028\u0029",
            "name": "allClasses",
            "summary": "Devuelve\u0020un\u0020array\u0020con\u0020todas\u0020las\u0020filas\u0020de\u0020la\u0020tabla\u0020class",
            "url": "classes/OpClass.html#method_allClasses"
        },                {
            "fqsen": "\\OpClass\u003A\u003AgetClassById\u0028\u0029",
            "name": "getClassById",
            "summary": "Devuelve\u0020el\u0020nombre\u0020de\u0020la\u0020clase\u0020del\u0020operador\u0020pasado\u0020por\u0020id",
            "url": "classes/OpClass.html#method_getClassById"
        },                {
            "fqsen": "\\OpClass\u003A\u003A\u0024ClassId",
            "name": "ClassId",
            "summary": "",
            "url": "classes/OpClass.html#property_ClassId"
        },                {
            "fqsen": "\\OpClass\u003A\u003A\u0024ClassName",
            "name": "ClassName",
            "summary": "",
            "url": "classes/OpClass.html#property_ClassName"
        },                {
            "fqsen": "\\Operator",
            "name": "Operator",
            "summary": "",
            "url": "classes/Operator.html"
        },                {
            "fqsen": "\\Operator\u003A\u003AallOperators\u0028\u0029",
            "name": "allOperators",
            "summary": "Devuelve\u0020un\u0020array\u0020con\u0020todos\u0020los\u0020operadores\u0020de\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/Operator.html#method_allOperators"
        },                {
            "fqsen": "\\Operator\u003A\u003AgetOperatorById\u0028\u0029",
            "name": "getOperatorById",
            "summary": "Devuelve\u0020el\u0020operador\u0020por\u0020id\u0020pasada",
            "url": "classes/Operator.html#method_getOperatorById"
        },                {
            "fqsen": "\\Operator\u003A\u003AgetOperatorsByRarity\u0028\u0029",
            "name": "getOperatorsByRarity",
            "summary": "Devuelve\u0020todos\u0020los\u0020operadores\u0020por\u0020rareza\u0020pasada",
            "url": "classes/Operator.html#method_getOperatorsByRarity"
        },                {
            "fqsen": "\\Operator\u003A\u003AgetRandomOperator\u0028\u0029",
            "name": "getRandomOperator",
            "summary": "Devulve\u0020un\u0020operador\u0020aleatorio",
            "url": "classes/Operator.html#method_getRandomOperator"
        },                {
            "fqsen": "\\Operator\u003A\u003AgetOpId\u0028\u0029",
            "name": "getOpId",
            "summary": "Get\u0020the\u0020value\u0020of\u0020OpId",
            "url": "classes/Operator.html#method_getOpId"
        },                {
            "fqsen": "\\Operator\u003A\u003AgetRarity\u0028\u0029",
            "name": "getRarity",
            "summary": "Get\u0020the\u0020value\u0020of\u0020Rarity",
            "url": "classes/Operator.html#method_getRarity"
        },                {
            "fqsen": "\\Operator\u003A\u003AsetRarity\u0028\u0029",
            "name": "setRarity",
            "summary": "Set\u0020the\u0020value\u0020of\u0020Rarity",
            "url": "classes/Operator.html#method_setRarity"
        },                {
            "fqsen": "\\Operator\u003A\u003AgetOpName\u0028\u0029",
            "name": "getOpName",
            "summary": "Get\u0020the\u0020value\u0020of\u0020OpName",
            "url": "classes/Operator.html#method_getOpName"
        },                {
            "fqsen": "\\Operator\u003A\u003AsetOpName\u0028\u0029",
            "name": "setOpName",
            "summary": "Set\u0020the\u0020value\u0020of\u0020OpName",
            "url": "classes/Operator.html#method_setOpName"
        },                {
            "fqsen": "\\Operator\u003A\u003AgetOpImg\u0028\u0029",
            "name": "getOpImg",
            "summary": "Get\u0020the\u0020value\u0020of\u0020OpImg",
            "url": "classes/Operator.html#method_getOpImg"
        },                {
            "fqsen": "\\Operator\u003A\u003AsetOpImg\u0028\u0029",
            "name": "setOpImg",
            "summary": "Set\u0020the\u0020value\u0020of\u0020OpImg",
            "url": "classes/Operator.html#method_setOpImg"
        },                {
            "fqsen": "\\Operator\u003A\u003AgetOpIcon\u0028\u0029",
            "name": "getOpIcon",
            "summary": "Get\u0020the\u0020value\u0020of\u0020OpIcon",
            "url": "classes/Operator.html#method_getOpIcon"
        },                {
            "fqsen": "\\Operator\u003A\u003AsetOpIcon\u0028\u0029",
            "name": "setOpIcon",
            "summary": "Set\u0020the\u0020value\u0020of\u0020OpIcon",
            "url": "classes/Operator.html#method_setOpIcon"
        },                {
            "fqsen": "\\Operator\u003A\u003AgetDescription\u0028\u0029",
            "name": "getDescription",
            "summary": "Get\u0020the\u0020value\u0020of\u0020Description",
            "url": "classes/Operator.html#method_getDescription"
        },                {
            "fqsen": "\\Operator\u003A\u003AsetDescription\u0028\u0029",
            "name": "setDescription",
            "summary": "Set\u0020the\u0020value\u0020of\u0020Description",
            "url": "classes/Operator.html#method_setDescription"
        },                {
            "fqsen": "\\Operator\u003A\u003AgetSkill1\u0028\u0029",
            "name": "getSkill1",
            "summary": "Get\u0020the\u0020value\u0020of\u0020Skill1",
            "url": "classes/Operator.html#method_getSkill1"
        },                {
            "fqsen": "\\Operator\u003A\u003AsetSkill1\u0028\u0029",
            "name": "setSkill1",
            "summary": "Set\u0020the\u0020value\u0020of\u0020Skill1",
            "url": "classes/Operator.html#method_setSkill1"
        },                {
            "fqsen": "\\Operator\u003A\u003AgetSkill2\u0028\u0029",
            "name": "getSkill2",
            "summary": "Get\u0020the\u0020value\u0020of\u0020Skill2",
            "url": "classes/Operator.html#method_getSkill2"
        },                {
            "fqsen": "\\Operator\u003A\u003AsetSkill2\u0028\u0029",
            "name": "setSkill2",
            "summary": "Set\u0020the\u0020value\u0020of\u0020Skill2",
            "url": "classes/Operator.html#method_setSkill2"
        },                {
            "fqsen": "\\Operator\u003A\u003AgetSkill3\u0028\u0029",
            "name": "getSkill3",
            "summary": "Get\u0020the\u0020value\u0020of\u0020Skill3",
            "url": "classes/Operator.html#method_getSkill3"
        },                {
            "fqsen": "\\Operator\u003A\u003AsetSkill3\u0028\u0029",
            "name": "setSkill3",
            "summary": "Set\u0020the\u0020value\u0020of\u0020Skill3",
            "url": "classes/Operator.html#method_setSkill3"
        },                {
            "fqsen": "\\Operator\u003A\u003A\u0024OpId",
            "name": "OpId",
            "summary": "",
            "url": "classes/Operator.html#property_OpId"
        },                {
            "fqsen": "\\Operator\u003A\u003A\u0024Rarity",
            "name": "Rarity",
            "summary": "",
            "url": "classes/Operator.html#property_Rarity"
        },                {
            "fqsen": "\\Operator\u003A\u003A\u0024OpName",
            "name": "OpName",
            "summary": "",
            "url": "classes/Operator.html#property_OpName"
        },                {
            "fqsen": "\\Operator\u003A\u003A\u0024OpImg",
            "name": "OpImg",
            "summary": "",
            "url": "classes/Operator.html#property_OpImg"
        },                {
            "fqsen": "\\Operator\u003A\u003A\u0024OpIcon",
            "name": "OpIcon",
            "summary": "",
            "url": "classes/Operator.html#property_OpIcon"
        },                {
            "fqsen": "\\Operator\u003A\u003A\u0024Description",
            "name": "Description",
            "summary": "",
            "url": "classes/Operator.html#property_Description"
        },                {
            "fqsen": "\\Operator\u003A\u003A\u0024Skill1",
            "name": "Skill1",
            "summary": "",
            "url": "classes/Operator.html#property_Skill1"
        },                {
            "fqsen": "\\Operator\u003A\u003A\u0024Skill2",
            "name": "Skill2",
            "summary": "",
            "url": "classes/Operator.html#property_Skill2"
        },                {
            "fqsen": "\\Operator\u003A\u003A\u0024Skill3",
            "name": "Skill3",
            "summary": "",
            "url": "classes/Operator.html#property_Skill3"
        },                {
            "fqsen": "\\Tag",
            "name": "Tag",
            "summary": "",
            "url": "classes/Tag.html"
        },                {
            "fqsen": "\\Tag\u003A\u003AgetTagId\u0028\u0029",
            "name": "getTagId",
            "summary": "",
            "url": "classes/Tag.html#method_getTagId"
        },                {
            "fqsen": "\\Tag\u003A\u003AgetTagName\u0028\u0029",
            "name": "getTagName",
            "summary": "",
            "url": "classes/Tag.html#method_getTagName"
        },                {
            "fqsen": "\\Tag\u003A\u003AsetTagName\u0028\u0029",
            "name": "setTagName",
            "summary": "",
            "url": "classes/Tag.html#method_setTagName"
        },                {
            "fqsen": "\\Tag\u003A\u003AallTags\u0028\u0029",
            "name": "allTags",
            "summary": "Devuelve\u0020todos\u0020los\u0020tags\u0020de\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/Tag.html#method_allTags"
        },                {
            "fqsen": "\\Tag\u003A\u003A\u0024TagId",
            "name": "TagId",
            "summary": "",
            "url": "classes/Tag.html#property_TagId"
        },                {
            "fqsen": "\\Tag\u003A\u003A\u0024TagName",
            "name": "TagName",
            "summary": "",
            "url": "classes/Tag.html#property_TagName"
        },                {
            "fqsen": "\\User",
            "name": "User",
            "summary": "",
            "url": "classes/User.html"
        },                {
            "fqsen": "\\User\u003A\u003AgetUsId\u0028\u0029",
            "name": "getUsId",
            "summary": "",
            "url": "classes/User.html#method_getUsId"
        },                {
            "fqsen": "\\User\u003A\u003AgetUsName\u0028\u0029",
            "name": "getUsName",
            "summary": "",
            "url": "classes/User.html#method_getUsName"
        },                {
            "fqsen": "\\User\u003A\u003AgetPassword\u0028\u0029",
            "name": "getPassword",
            "summary": "",
            "url": "classes/User.html#method_getPassword"
        },                {
            "fqsen": "\\User\u003A\u003AgetEmail\u0028\u0029",
            "name": "getEmail",
            "summary": "",
            "url": "classes/User.html#method_getEmail"
        },                {
            "fqsen": "\\User\u003A\u003AsetUsName\u0028\u0029",
            "name": "setUsName",
            "summary": "",
            "url": "classes/User.html#method_setUsName"
        },                {
            "fqsen": "\\User\u003A\u003AsetEmail\u0028\u0029",
            "name": "setEmail",
            "summary": "",
            "url": "classes/User.html#method_setEmail"
        },                {
            "fqsen": "\\User\u003A\u003AsetPassword\u0028\u0029",
            "name": "setPassword",
            "summary": "",
            "url": "classes/User.html#method_setPassword"
        },                {
            "fqsen": "\\User\u003A\u003AallUsers\u0028\u0029",
            "name": "allUsers",
            "summary": "Devuelve\u0020todos\u0020los\u0020usuarios\u0020de\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/User.html#method_allUsers"
        },                {
            "fqsen": "\\User\u003A\u003AcheckLogIn\u0028\u0029",
            "name": "checkLogIn",
            "summary": "Comprueba\u0020si\u0020el\u0020usuario\u0020introducido\u0020en\u0020el\u0020login\u0020es\u0020v\u00E1lido",
            "url": "classes/User.html#method_checkLogIn"
        },                {
            "fqsen": "\\User\u003A\u003AaddUser\u0028\u0029",
            "name": "addUser",
            "summary": "Crea\u0020un\u0020usuario\u0020en\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/User.html#method_addUser"
        },                {
            "fqsen": "\\User\u003A\u003AupdateUser\u0028\u0029",
            "name": "updateUser",
            "summary": "Edita\u0020un\u0020usuario\u0020de\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/User.html#method_updateUser"
        },                {
            "fqsen": "\\User\u003A\u003AdeleteUser\u0028\u0029",
            "name": "deleteUser",
            "summary": "Elimina\u0020a\u0020un\u0020usuario\u0020de\u0020la\u0020base\u0020de\u0020datos",
            "url": "classes/User.html#method_deleteUser"
        },                {
            "fqsen": "\\User\u003A\u003AgetUserById\u0028\u0029",
            "name": "getUserById",
            "summary": "Devuelve\u0020usuario\u0020por\u0020id\u0020pasado",
            "url": "classes/User.html#method_getUserById"
        },                {
            "fqsen": "\\User\u003A\u003A\u0024UsId",
            "name": "UsId",
            "summary": "",
            "url": "classes/User.html#property_UsId"
        },                {
            "fqsen": "\\User\u003A\u003A\u0024UsName",
            "name": "UsName",
            "summary": "",
            "url": "classes/User.html#property_UsName"
        },                {
            "fqsen": "\\User\u003A\u003A\u0024Password",
            "name": "Password",
            "summary": "",
            "url": "classes/User.html#property_Password"
        },                {
            "fqsen": "\\User\u003A\u003A\u0024Email",
            "name": "Email",
            "summary": "",
            "url": "classes/User.html#property_Email"
        },                {
            "fqsen": "\\runMyFunction\u0028\u0029",
            "name": "runMyFunction",
            "summary": "",
            "url": "namespaces/default.html#function_runMyFunction"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        }            ]
);
